---
name: xfce-i3
description: My own spin of Fedora Atomic Vauxite (XFCE) with i3

base-image: quay.io/fedora-ostree-desktops/vauxite
image-version: 40

modules:
  - type: files
    files:
      - source: system
        destination: /
  - type: rpm-ostree
    install:
      - i3
      - rofi
      - nvim
  - type: default-flatpaks
    notify: true
    system:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "Flathub (system-wide)"
      install:
        - com.borgbase.Vorta
        - com.brave.Browser
        - com.jetbrains.IntelliJ-IDEA-Ultimate
        - com.plexamp.Plexamp
  - type: signing
