---
name: xfce-i3
description: My own spin of Fedora Atomic Vauxite (XFCE) with i3

base-image: quay.io/fedora-ostree-desktops/vauxite
image-version: 40

modules:
  - type: files
    files:
      - source: system
        destination: /
  - type: rpm-ostree
    repos:
      - https://download.docker.com/linux/fedora/docker-ce.repo
    install:
      - lightdm
      - slick-greeter
      - i3
      - rofi
      - picom
      - zsh
      - neovim
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
      - power-profiles-daemon
    remove:
      - lightdm-gtk
  - type: default-flatpaks
    notify: true
    system:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "Flathub (system-wide)"
      install:
        - com.borgbase.Vorta
        - com.brave.Browser
        - com.discordapp.Discord
        - com.jetbrains.IntelliJ-IDEA-Ultimate
        - com.plexamp.Plexamp
        - com.valvesoftware.Steam
  - type: signing
