---
name: xfce-i3
description: My own spin of Fedora Atomic uCore with XFCE4 and i3

base-image: quay.io/fedora-ostree-desktops/base
image-version: 40

modules:
  - type: files
    files:
      - source: system
        destination: /
  - type: rpm-ostree
    install:
      - xfce-desktop
      - i3
  - type: default-flatpaks
    notify: true
    system:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "Flathub (system-wide)"
      install:
        - com.brave.Browser
  - type: signing
